>>>>> no number of cores provided or running in environment unsupportive of parallelized testing, not running multiprocessing <<<<<
============================= test session starts ==============================
platform linux -- Python 3.7.2, pytest-4.5.0, py-1.8.0, pluggy-0.11.0
rootdir: /home/jrusnak/workspace/pytest_mproc
plugins: metadata-1.8.0, html-1.20.0, cov-2.7.1
collected 0 items / 2 errors

==================================== ERRORS ====================================
___________________ ERROR collecting test/test_mproc_runs.py ___________________
ImportError while importing test module '/home/jrusnak/workspace/pytest_mproc/test/test_mproc_runs.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_mproc_runs.py:10: in <module>
    from pytest_mproc_utils import pytest_mproc_global_finalizer, pytest_mproc_global_initializer
E   ModuleNotFoundError: No module named 'pytest_mproc_utils'
____________________ ERROR collecting test/test_output.txt _____________________
/usr/local/lib/python3.7/doctest.py:668: in get_doctest
    return DocTest(self.get_examples(string, name), globs,
/usr/local/lib/python3.7/doctest.py:682: in get_examples
    return [x for x in self.parse(string, name)
/usr/local/lib/python3.7/doctest.py:644: in parse
    self._parse_example(m, name, lineno)
/usr/local/lib/python3.7/doctest.py:702: in _parse_example
    self._check_prompt_blank(source_lines, indent, name, lineno)
/usr/local/lib/python3.7/doctest.py:789: in _check_prompt_blank
    line[indent:indent+3], line))
E   ValueError: line 1 of the docstring for test_output.txt lacks blank after >>>: '>>>>> no number of cores provided or running in environment unsupportive of parallelized testing, not running multiprocessing <<<<<'
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 2 error in 0.57 seconds ============================
