>>>>> no number of cores provided, not running multiprocessing <<<<<
============================= test session starts ==============================
platform darwin -- Python 3.7.7, pytest-5.4.1, py-1.7.0, pluggy-0.13.1
rootdir: /Users/jrusnak/workspace/OSS/pytest_mproc
plugins: forked-1.0.2, asyncio-0.10.0, html-1.20.0, cov-2.6.0, xdist-1.31.0, metadata-1.8.0
collected 1006 items / 1 error / 1005 selected

###### INITIALIZE ############


###### FINALIZE ############


==================================== ERRORS ====================================
____________________ ERROR collecting test/test_output.txt _____________________
/export/apps/python/3.7/lib/python3.7/doctest.py:668: in get_doctest
    return DocTest(self.get_examples(string, name), globs,
/export/apps/python/3.7/lib/python3.7/doctest.py:682: in get_examples
    return [x for x in self.parse(string, name)
/export/apps/python/3.7/lib/python3.7/doctest.py:644: in parse
    self._parse_example(m, name, lineno)
/export/apps/python/3.7/lib/python3.7/doctest.py:702: in _parse_example
    self._check_prompt_blank(source_lines, indent, name, lineno)
/export/apps/python/3.7/lib/python3.7/doctest.py:789: in _check_prompt_blank
    line[indent:indent+3], line))
E   ValueError: line 1 of the docstring for test_output.txt lacks blank after >>>: '>>>>> no number of cores provided, not running multiprocessing <<<<<'
=========================== short test summary info ============================
ERROR test_output.txt - ValueError: line 1 of the docstring for test_output.t...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.30s ===============================
